# Generated by Django 3.2.8 on 2021-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_title',
            new_name='title_car',
        ),
        migrations.AddField(
            model_name='contact',
            name='car_id',
            field=models.IntegerField(default=0),
        ),
    ]
